import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";

export const Experiences = [
  {
    title: "Bootcamp Graduate",
    location: "Online",
    company: "Academia X",
    description:
      "I graduated after 6 months of study. During this time, I practiced with my own projects, built web pages, cloned existing websites, and studied in more depth everything I learned in the bootcamp.",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "React.js",
      "Node.js",
      "Express",
      "PostgreSQL",
    ],
    date: "2022",
    icon: "/graduate-white.png",
  },
  {
    title: "Trainee Frontend Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Completed a frontend development internship, gaining hands-on experience with the company’s project architecture and workflow management. Developed simple UI components, implemented core functionalities, and resolved various technical issues.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "Git",
      "GitHub",
    ],
    date: "January 2023 - May 2023",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Junior Frontend Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Worked as a key member of the product development team, responsible for designing, developing, and maintaining web applications using Next.js. Led the frontend development of several projects while collaborating with cross-functional teams on others. Implemented global state management solutions and integrated APIs using Redux Toolkit and REST APIs.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "REST APIs",
      "Git",
      "GitHub",
    ],
    date: "May 2023 - August 2024",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Trainee Full Stack Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Functioned as a full stack developer, handling both frontend and backend tasks. On the backend, implemented business logic using Node.js and Express.js, developed APIs, and managed databases like MongoDB and PostgreSQL. On the frontend, continued building and enhancing React applications, integrating both REST APIs and GraphQL for efficient data handling.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "Node.js",
      "Express.js",
      "MongoDB",
      "PostgreSQL",
      "REST APIs",
      "GraphQL",
      "Git",
      "GitHub",
      "Docker",
      "Postman",
    ],
    date: "May 2024 - August 2024",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Independent Full Stack Developer",
    location: "Toronto, Canada (Remote)",
    company: "Personal Projects & Freelance",
    description:
      "Focused on building production-grade applications and advancing my expertise as a frontend developer with solid backend foundations. Designed and developed multiple professional projects including Oli Store (custom e-commerce with a headless backend), Terrenas Realty (real estate platform with authentication, listings, and live chat), and Cliniq (modern SaaS solution for private clinics). Alongside hands-on development, I followed a structured roadmap to master React, Next.js, TypeScript, Node.js, Express, and databases like MongoDB and PostgreSQL. This phase strengthened my skills in clean architecture, scalable UI design, and fullstack development.",
    technologies: [
      "Next.js",
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "PostgreSQL",
      "Prisma",
      "REST APIs",
      "GraphQL",
      "Git",
      "GitHub",
      "Docker",
    ],
    date: "September 2024 - Present",
    icon: "/jordisdev-logo.png",
  },
];
