import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";

export const Experiences = [
  {
    title: "Full Stack Developer",
    location: "Toronto, Canada / Dominican Republic (Remote)",
    company: "Bill Med International Inc.",
    description:
      "Develop and maintain a full-stack medical management platform for international medical billing and healthcare operations. The system manages patient cases, insurance claims, invoices, payments, financial reports, claim follow-ups, notifications, and PDF invoice/claim generation. I work across the frontend and backend, building reusable UI components, dynamic tables, filters, dashboards, REST API endpoints, database models, reporting logic, authentication, role-based access control, and workflow automation for real business operations.",
    technologies: [
      "Next.js",
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "Prisma",
      "PostgreSQL",
      "REST APIs",
      "TanStack React Query",
      "Zustand",
      "Docker",
      "Postman",
      "jsPDF",
      "Git",
      "GitHub",
    ],
    date: "November 2025 - Present",
    icon: "/experience/bill_med_logo.png",
  },
  {
    title: "Independent Full Stack Developer",
    location: "Toronto, Canada (Remote)",
    company: "Personal Projects & Freelance",
    description:
      "Built production-focused web applications to strengthen my professional software development skills. Designed and developed projects such as Oli Store, a custom e-commerce platform with a modern frontend and headless backend integration; Terrenas Realty, a real estate platform with authentication, property listings, post management, and live chat; and Cliniq, a modern SaaS solution for private clinics. This phase helped me improve my ability to build scalable interfaces, integrate APIs, structure backend services, manage databases, and create complete full-stack applications.",
    technologies: [
      "Next.js",
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "PostgreSQL",
      "Prisma",
      "REST APIs",
      "GraphQL",
      "Git",
      "GitHub",
      "Docker",
    ],
    date: "September 2024 - Present",
    icon: "/jordisdev-logo.png",
  },
  {
    title: "Trainee Full Stack Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Functioned as a full stack developer, handling both frontend and backend tasks. On the backend, implemented business logic using Node.js and Express.js, developed APIs, and managed databases like MongoDB and PostgreSQL. On the frontend, continued building and enhancing React applications, integrating both REST APIs and GraphQL for efficient data handling.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "Node.js",
      "Express.js",
      "MongoDB",
      "PostgreSQL",
      "REST APIs",
      "GraphQL",
      "Git",
      "GitHub",
      "Docker",
      "Postman",
    ],
    date: "May 2024 - August 2024",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Junior Frontend Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Worked as a key member of the product development team, responsible for designing, developing, and maintaining web applications using Next.js. Led the frontend development of several projects while collaborating with cross-functional teams on others. Implemented global state management solutions and integrated APIs using Redux Toolkit and REST APIs.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "REST APIs",
      "Git",
      "GitHub",
    ],
    date: "May 2023 - August 2024",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Trainee Frontend Developer",
    location: "Colombia (Remote)",
    company: "Nevobit",
    description:
      "Completed a frontend development internship, gaining hands-on experience with the company’s project architecture and workflow management. Developed simple UI components, implemented core functionalities, and resolved various technical issues.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript (ES6+)",
      "TypeScript",
      "React.js",
      "Next.js",
      "Redux Toolkit",
      "Git",
      "GitHub",
    ],
    date: "January 2023 - May 2023",
    icon: "/experience/nevobit.png",
  },
  {
    title: "Bootcamp Graduate",
    location: "Online",
    company: "Academia X",
    description:
      "Completed a full stack development bootcamp focused on web development fundamentals and practical project building. Studied HTML, CSS, JavaScript, React, Node.js, Express, and PostgreSQL while building web pages, cloning existing websites, practicing programming concepts, and developing personal projects to strengthen my frontend and backend foundations.",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "React.js",
      "Node.js",
      "Express",
      "PostgreSQL",
    ],
    date: "2022",
    icon: "/graduate-white.png",
  },
];